# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PyProjects\lab03\ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 700)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.centralFrame = QtWidgets.QFrame(self.centralWidget)
        self.centralFrame.setEnabled(True)
        self.centralFrame.setGeometry(QtCore.QRect(10, 10, 460, 680))
        self.centralFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralFrame.setStyleSheet("QLabel{\n"
"    color: rgb(2, 200, 255);\n"
"}\n"
"\n"
"QFrame[objectName^=\"centralFrame\"] {\n"
"background-color: rgb(28, 33, 38);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QFrame[objectName^=\"titleBar\"] {\n"
"background-color: none;\n"
"}\n"
"\n"
"QPushButton[objectName^=\"closeButton\"] {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}\n"
"\n"
"QPushButton[objectName^=\"closeButton\"]:hover {        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton[objectName^=\"minimizeButton\"] {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgba(255, 245, 0, 150);\n"
"}\n"
"\n"
"QPushButton[objectName^=\"minimizeButton\"]:hover {        \n"
"    background-color: rgb(255, 245, 0);\n"
"}\n"
"\n"
"QLabel[objectName^=\"titleLabel\"]{\n"
"    font: 11pt \"Tahoma\";\n"
"    color: rgb(2, 200, 255);\n"
"}\n"
"\n"
"QPushButton {        \n"
"    border-style: outset;\n"
"    border: 1px solid;\n"
"    alternate-background-color: rgb(255, 255, 0);\n"
"    background-color: rgba(0, 200, 0, 150);\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;    \n"
"    font: 10pt \"Yu Gothic UI\";\n"
"    padding-bottom: 3px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 200, 0);\n"
"    border-style: inset;\n"
"    border-bottom-color: \"gray\";\n"
"}\n"
"\n"
"QPushButton[objectName^=\"enterButton\"] {        \n"
"    border-style: outset;\n"
"    border: 1px solid;\n"
"    alternate-background-color: rgb(255, 255, 0);\n"
"    background-color: rgba(255, 0, 0, 150);\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;    \n"
"    font: 12pt \"Yu Gothic UI\";\n"
"    padding-bottom: 3px;\n"
"}\n"
"\n"
"QPushButton#enterButton:pressed {\n"
"    background-color: rgb(200, 0, 0);\n"
"    border-style: inset;\n"
"    border-bottom-color: \"gray\";\n"
"}\n"
"\n"
"QListWidget{\n"
"    background-color: #8AC8FF;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #8AC8FF;\n"
"    border: 1px solid rgb(52, 59, 72);\n"
"}\n"
"\n"
"QTextEdit{\n"
"    background-color: #8AC8FF;\n"
"    border: 1px solid rgb(52, 59, 72);\n"
"}\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-image: url(cil-check.png);\n"
"    background: 3px solid #8AC8FF;\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"")
        self.centralFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.centralFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centralFrame.setObjectName("centralFrame")
        self.titleBar = QtWidgets.QFrame(self.centralFrame)
        self.titleBar.setEnabled(True)
        self.titleBar.setGeometry(QtCore.QRect(0, 0, 460, 40))
        self.titleBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.btnsFrame = QtWidgets.QFrame(self.titleBar)
        self.btnsFrame.setEnabled(True)
        self.btnsFrame.setGeometry(QtCore.QRect(360, 0, 100, 40))
        self.btnsFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btnsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnsFrame.setObjectName("btnsFrame")
        self.closeButton = QtWidgets.QPushButton(self.btnsFrame)
        self.closeButton.setEnabled(True)
        self.closeButton.setGeometry(QtCore.QRect(67, 12, 17, 17))
        self.closeButton.setStyleSheet("")
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.minimizeButton = QtWidgets.QPushButton(self.btnsFrame)
        self.minimizeButton.setEnabled(True)
        self.minimizeButton.setGeometry(QtCore.QRect(40, 12, 17, 17))
        self.minimizeButton.setMinimumSize(QtCore.QSize(16, 16))
        self.minimizeButton.setMaximumSize(QtCore.QSize(17, 17))
        self.minimizeButton.setText("")
        self.minimizeButton.setObjectName("minimizeButton")
        self.titleFrame = QtWidgets.QFrame(self.titleBar)
        self.titleFrame.setGeometry(QtCore.QRect(0, 0, 360, 40))
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.titleLabel = QtWidgets.QLabel(self.titleFrame)
        self.titleLabel.setGeometry(QtCore.QRect(15, 0, 345, 40))
        self.titleLabel.setObjectName("titleLabel")
        self.titleFrame.raise_()
        self.btnsFrame.raise_()
        self.createFolderButton = QtWidgets.QPushButton(self.centralFrame)
        self.createFolderButton.setEnabled(True)
        self.createFolderButton.setGeometry(QtCore.QRect(315, 170, 125, 24))
        self.createFolderButton.setObjectName("createFolderButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralFrame)
        self.lineEdit.setGeometry(QtCore.QRect(15, 130, 430, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.createFileButton = QtWidgets.QPushButton(self.centralFrame)
        self.createFileButton.setEnabled(True)
        self.createFileButton.setGeometry(QtCore.QRect(170, 170, 125, 24))
        self.createFileButton.setObjectName("createFileButton")
        self.mainLabel = QtWidgets.QLabel(self.centralFrame)
        self.mainLabel.setGeometry(QtCore.QRect(40, 40, 381, 71))
        self.mainLabel.setObjectName("mainLabel")
        self.textEdit = QtWidgets.QTextEdit(self.centralFrame)
        self.textEdit.setGeometry(QtCore.QRect(15, 220, 430, 400))
        self.textEdit.setObjectName("textEdit")
        self.infoButton = QtWidgets.QPushButton(self.centralFrame)
        self.infoButton.setEnabled(True)
        self.infoButton.setGeometry(QtCore.QRect(20, 170, 125, 24))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.infoButton.setFont(font)
        self.infoButton.setObjectName("infoButton")
        self.cmdButton = QtWidgets.QPushButton(self.centralFrame)
        self.cmdButton.setEnabled(True)
        self.cmdButton.setGeometry(QtCore.QRect(160, 640, 125, 24))
        self.cmdButton.setObjectName("cmdButton")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.minimizeButton, self.closeButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.centralFrame.setAccessibleName(_translate("MainWindow", "centralFrame"))
        self.closeButton.setAccessibleName(_translate("MainWindow", "closeButton"))
        self.minimizeButton.setToolTip(_translate("MainWindow", "Minimize"))
        self.minimizeButton.setAccessibleName(_translate("MainWindow", "minimizeButton"))
        self.titleLabel.setAccessibleName(_translate("MainWindow", "titleLabel"))
        self.titleLabel.setText(_translate("MainWindow", "Lab Project 03 - Balabin"))
        self.createFolderButton.setAccessibleName(_translate("MainWindow", "testButton"))
        self.createFolderButton.setText(_translate("MainWindow", "Создать Папку"))
        self.createFileButton.setAccessibleName(_translate("MainWindow", "testButton"))
        self.createFileButton.setText(_translate("MainWindow", "Создать Файл"))
        self.mainLabel.setAccessibleName(_translate("MainWindow", "titleLabel"))
        self.mainLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Файловая система EXT, ограничение:</span></p><p><span style=\" font-size:12pt;\">максимальная длина имени файла - </span><span style=\" font-size:10pt;\">255</span></p></body></html>"))
        self.infoButton.setAccessibleName(_translate("MainWindow", "testButton"))
        self.infoButton.setText(_translate("MainWindow", "Информация"))
        self.cmdButton.setAccessibleName(_translate("MainWindow", "testButton"))
        self.cmdButton.setText(_translate("MainWindow", "CMD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
